### PR TITLE
Add flags to stats command

### PR DESCRIPTION
**Pull request by Palmidence**

### CODE REVIEW

**Comment by AustinLMayes** [comment]
Flag totals are not counted as part of the statistical analysis algorithms in use by the backend to calculate these totals. This opens up the debate if we should count flags at this point because changing these analyses could have effects on leaderboards and other historical data. 

Leaving this for @Electroid to decide.

These changes will not work unless changes are made to the following files:
https://github.com/StratusNetwork/web/blob/bc3b5432f9cd9a9c1b960a3d7654cf32b87fbb22/script/player-stats.js
https://github.com/StratusNetwork/web/blob/bc3b5432f9cd9a9c1b960a3d7654cf32b87fbb22/app/models/player_stat.rb

**Comment by Electroid** [comment]
For now, I think we'll keep stats as is and not count flags.

**Comment by Palmidence** [comment]
I noticed you said, "For now". Should this be kept open for the future, or should I close it?

**Comment by AustinLMayes** [comment]
Closed in favor of adding to the rewrite

**Pull request closed without merging**
