### PR TITLE
fixes polls exposing player realname

### PR DESCRIPTION
**Pull request by PotatoStealer**

### CODE REVIEW

**Comment by Electroid** [comment]
Problem is if the person is nicked, the message doesn't show up at all. You need to find the player's `User` document then send a `PlayerComponent`. This might be too complicated, in which case, just leave that bug be.

**Comment by Electroid** [comment]
Don't touch too much of polls (the code is ancient and will likely be re-written one day), just change the `getInitiator` object to return a `@Nullable PlayerId` and then you can use that to create a `PlayerComponent`.

**Comment by PotatoStealer** [comment]
I think I'll leave the PR here first, since it looks like an ugly fix to me at the point of writing - until the code is re-written.

**Comment by amactus** [comment]
so @Electroid @PotatoStealer is it better to have the message not show when someone is nicked, or do the fix electroid proposed. This is still an issue, and waiting for a re-write makes little sense

**Comment by AustinLMayes** [comment]
Closed in favor of #67

**Pull request closed without merging**
