### PR TITLE
Teleport observers to default spawnpoint instead of cancelling event

### PR DESCRIPTION
**Pull request by PotatoStealer**
title says everything

### CODE REVIEW

**Comment by Electroid** [comment]
There is a reason this change was made. Players would sometimes get caught in infinite teleport loops, not sure if that's addressed here.

**Comment by PotatoStealer** [comment]
how so? and is there an exact reason for it?

**Comment by Pablete1234** [comment]
You may want to set the "to" location of the event to the spawn location instead of teleporting them, and also you'll need to test the infinite TP thing that used to be an issue

**Comment by PotatoStealer** [comment]
I don't think I can test the teleport loop on my local server. Perhaps get it live-tested on the servers and instantly revert it if such cases happen?

**Comment by AustinLMayes** [comment]
Closed because stale and as Electroid said, the change was made for a reason.

Open for consideration during the rewrite.

**Pull request closed without merging**
