### PR TITLE
Enhance dynamic rotations broadcast & logic

### PR DESCRIPTION
**Pull request by javipepe**
|                                             | Before                          | Now                                                    |
|---------------------------------------------|---------------------------------|--------------------------------------------------------|
| Player Count considered for rotation change | Number of participating players | Number of participating players + (observer count / 2) |
| Broadcast                                   | See server                      |  (Click to enlarge)                                                    |

:sparkles:

### CODE REVIEW

**Comment by Pablete1234** [comment]
i'd propose a message of something along the lines of:

The server switched rotation from `mini` to `medium` rotation so that it can better accomodate the current player count.

**Comment by javipepe** [comment]
@Pablete1234  IIRC that's how it was before (more or less) and I was told to change it. Personally, I think both look alright :+1:

**Comment by Pablete1234** [comment]
the message before didn't include formatting thingies on top or bottom, didn't include the actual names of changed rotations, and had ugly colors, all my message aims to replace is the  "previous rot" and "current rot" messages, because they can easily be included in the bottom one

**Comment by amactus** [comment]
Looks good for now.

**Pull request merged**
